// Full country/currency/dial-code dataset used by profile setup.

export type Country = {
  name: string;
  code: string;
  flag: string;
  dial: string;
  currency: string;
  currencyName: string;
  currencySymbol: string;
};

const COUNTRIES_CURRENCIES = [
  { country: "Afghanistan", code: "AF", currency: "AFN", symbol: "؋", name: "Afghan Afghani" },
  { country: "Albania", code: "AL", currency: "ALL", symbol: "L", name: "Albanian Lek" },
  { country: "Algeria", code: "DZ", currency: "DZD", symbol: "د.ج", name: "Algerian Dinar" },
  { country: "Andorra", code: "AD", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Angola", code: "AO", currency: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
  { country: "Anguilla", code: "AI", currency: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { country: "Antigua and Barbuda", code: "AG", currency: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { country: "Argentina", code: "AR", currency: "ARS", symbol: "$", name: "Argentine Peso" },
  { country: "Armenia", code: "AM", currency: "AMD", symbol: "֏", name: "Armenian Dram" },
  { country: "Aruba", code: "AW", currency: "AWG", symbol: "ƒ", name: "Aruban Florin" },
  { country: "Australia", code: "AU", currency: "AUD", symbol: "$", name: "Australian Dollar" },
  { country: "Austria", code: "AT", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Azerbaijan", code: "AZ", currency: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
  { country: "Bahamas", code: "BS", currency: "BSD", symbol: "$", name: "Bahamian Dollar" },
  { country: "Bahrain", code: "BH", currency: "BHD", symbol: ".د.ب", name: "Bahraini Dinar" },
  { country: "Bangladesh", code: "BD", currency: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { country: "Barbados", code: "BB", currency: "BBD", symbol: "$", name: "Barbadian Dollar" },
  { country: "Belarus", code: "BY", currency: "BYN", symbol: "Br", name: "Belarusian Ruble" },
  { country: "Belgium", code: "BE", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Belize", code: "BZ", currency: "BZD", symbol: "$", name: "Belize Dollar" },
  { country: "Benin", code: "BJ", currency: "XOF", symbol: "Fr", name: "West African CFA Franc" },
  { country: "Bermuda", code: "BM", currency: "BMD", symbol: "$", name: "Bermudian Dollar" },
  { country: "Bhutan", code: "BT", currency: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum" },
  { country: "Bolivia", code: "BO", currency: "BOB", symbol: "Bs.", name: "Bolivian Boliviano" },
  { country: "Bosnia and Herzegovina", code: "BA", currency: "BAM", symbol: "KM", name: "Bosnia and Herzegovina Convertible Mark" },
  { country: "Botswana", code: "BW", currency: "BWP", symbol: "P", name: "Botswana Pula" },
  { country: "Brazil", code: "BR", currency: "BRL", symbol: "R$", name: "Brazilian Real" },
  { country: "Brunei", code: "BN", currency: "BND", symbol: "$", name: "Brunei Dollar" },
  { country: "Bulgaria", code: "BG", currency: "BGN", symbol: "лв", name: "Bulgarian Lev" },
  { country: "Burkina Faso", code: "BF", currency: "XOF", symbol: "Fr", name: "West African CFA Franc" },
  { country: "Burundi", code: "BI", currency: "BIF", symbol: "Fr", name: "Burundian Franc" },
  { country: "Cambodia", code: "KH", currency: "KHR", symbol: "៛", name: "Cambodian Riel" },
  { country: "Cameroon", code: "CM", currency: "XAF", symbol: "Fr", name: "Central African CFA Franc" },
  { country: "Canada", code: "CA", currency: "CAD", symbol: "$", name: "Canadian Dollar" },
  { country: "Cape Verde", code: "CV", currency: "CVE", symbol: "$", name: "Cape Verdean Escudo" },
  { country: "Cayman Islands", code: "KY", currency: "KYD", symbol: "$", name: "Cayman Islands Dollar" },
  { country: "Central African Republic", code: "CF", currency: "XAF", symbol: "Fr", name: "Central African CFA Franc" },
  { country: "Chad", code: "TD", currency: "XAF", symbol: "Fr", name: "Central African CFA Franc" },
  { country: "Chile", code: "CL", currency: "CLP", symbol: "$", name: "Chilean Peso" },
  { country: "China", code: "CN", currency: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { country: "Colombia", code: "CO", currency: "COP", symbol: "$", name: "Colombian Peso" },
  { country: "Comoros", code: "KM", currency: "KMF", symbol: "Fr", name: "Comorian Franc" },
  { country: "Congo (DRC)", code: "CD", currency: "CDF", symbol: "Fr", name: "Congolese Franc" },
  { country: "Congo (Republic)", code: "CG", currency: "XAF", symbol: "Fr", name: "Central African CFA Franc" },
  { country: "Costa Rica", code: "CR", currency: "CRC", symbol: "₡", name: "Costa Rican Colón" },
  { country: "Côte d'Ivoire", code: "CI", currency: "XOF", symbol: "Fr", name: "West African CFA Franc" },
  { country: "Croatia", code: "HR", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Cuba", code: "CU", currency: "CUP", symbol: "$", name: "Cuban Peso" },
  { country: "Curaçao", code: "CW", currency: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder" },
  { country: "Cyprus", code: "CY", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Czech Republic", code: "CZ", currency: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { country: "Denmark", code: "DK", currency: "DKK", symbol: "kr", name: "Danish Krone" },
  { country: "Djibouti", code: "DJ", currency: "DJF", symbol: "Fr", name: "Djiboutian Franc" },
  { country: "Dominica", code: "DM", currency: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { country: "Dominican Republic", code: "DO", currency: "DOP", symbol: "$", name: "Dominican Peso" },
  { country: "Ecuador", code: "EC", currency: "USD", symbol: "$", name: "United States Dollar" },
  { country: "Egypt", code: "EG", currency: "EGP", symbol: "£", name: "Egyptian Pound" },
  { country: "El Salvador", code: "SV", currency: "USD", symbol: "$", name: "United States Dollar" },
  { country: "Equatorial Guinea", code: "GQ", currency: "XAF", symbol: "Fr", name: "Central African CFA Franc" },
  { country: "Eritrea", code: "ER", currency: "ERN", symbol: "Nfk", name: "Eritrean Nakfa" },
  { country: "Estonia", code: "EE", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Eswatini", code: "SZ", currency: "SZL", symbol: "L", name: "Swazi Lilangeni" },
  { country: "Ethiopia", code: "ET", currency: "ETB", symbol: "Br", name: "Ethiopian Birr" },
  { country: "Fiji", code: "FJ", currency: "FJD", symbol: "$", name: "Fijian Dollar" },
  { country: "Finland", code: "FI", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "France", code: "FR", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Gabon", code: "GA", currency: "XAF", symbol: "Fr", name: "Central African CFA Franc" },
  { country: "Gambia", code: "GM", currency: "GMD", symbol: "D", name: "Gambian Dalasi" },
  { country: "Georgia", code: "GE", currency: "GEL", symbol: "₾", name: "Georgian Lari" },
  { country: "Germany", code: "DE", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Ghana", code: "GH", currency: "GHS", symbol: "₵", name: "Ghanaian Cedi" },
  { country: "Greece", code: "GR", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Grenada", code: "GD", currency: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { country: "Guatemala", code: "GT", currency: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
  { country: "Guinea", code: "GN", currency: "GNF", symbol: "Fr", name: "Guinean Franc" },
  { country: "Guinea-Bissau", code: "GW", currency: "XOF", symbol: "Fr", name: "West African CFA Franc" },
  { country: "Guyana", code: "GY", currency: "GYD", symbol: "$", name: "Guyanese Dollar" },
  { country: "Haiti", code: "HT", currency: "HTG", symbol: "G", name: "Haitian Gourde" },
  { country: "Honduras", code: "HN", currency: "HNL", symbol: "L", name: "Honduran Lempira" },
  { country: "Hong Kong", code: "HK", currency: "HKD", symbol: "$", name: "Hong Kong Dollar" },
  { country: "Hungary", code: "HU", currency: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { country: "Iceland", code: "IS", currency: "ISK", symbol: "kr", name: "Icelandic Króna" },
  { country: "India", code: "IN", currency: "INR", symbol: "₹", name: "Indian Rupee" },
  { country: "Indonesia", code: "ID", currency: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { country: "Iran", code: "IR", currency: "IRR", symbol: "﷼", name: "Iranian Rial" },
  { country: "Iraq", code: "IQ", currency: "IQD", symbol: "ع.د", name: "Iraqi Dinar" },
  { country: "Ireland", code: "IE", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Israel", code: "IL", currency: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { country: "Italy", code: "IT", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Jamaica", code: "JM", currency: "JMD", symbol: "$", name: "Jamaican Dollar" },
  { country: "Japan", code: "JP", currency: "JPY", symbol: "¥", name: "Japanese Yen" },
  { country: "Jordan", code: "JO", currency: "JOD", symbol: "د.ا", name: "Jordanian Dinar" },
  { country: "Kazakhstan", code: "KZ", currency: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  { country: "Kenya", code: "KE", currency: "KES", symbol: "KSh", name: "Kenyan Shilling" },
  { country: "Kiribati", code: "KI", currency: "AUD", symbol: "$", name: "Australian Dollar" },
  { country: "Kuwait", code: "KW", currency: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
  { country: "Kyrgyzstan", code: "KG", currency: "KGS", symbol: "лв", name: "Kyrgyzstani Som" },
  { country: "Laos", code: "LA", currency: "LAK", symbol: "₭", name: "Lao Kip" },
  { country: "Latvia", code: "LV", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Lebanon", code: "LB", currency: "LBP", symbol: "ل.ل", name: "Lebanese Pound" },
  { country: "Lesotho", code: "LS", currency: "LSL", symbol: "L", name: "Lesotho Loti" },
  { country: "Liberia", code: "LR", currency: "LRD", symbol: "$", name: "Liberian Dollar" },
  { country: "Libya", code: "LY", currency: "LYD", symbol: "ل.د", name: "Libyan Dinar" },
  { country: "Liechtenstein", code: "LI", currency: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { country: "Lithuania", code: "LT", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Luxembourg", code: "LU", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Macau", code: "MO", currency: "MOP", symbol: "P", name: "Macanese Pataca" },
  { country: "Madagascar", code: "MG", currency: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
  { country: "Malawi", code: "MW", currency: "MWK", symbol: "MK", name: "Malawian Kwacha" },
  { country: "Malaysia", code: "MY", currency: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { country: "Maldives", code: "MV", currency: "MVR", symbol: ".ރ", name: "Maldivian Rufiyaa" },
  { country: "Mali", code: "ML", currency: "XOF", symbol: "Fr", name: "West African CFA Franc" },
  { country: "Malta", code: "MT", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Mauritania", code: "MR", currency: "MRU", symbol: "UM", name: "Mauritanian Ouguiya" },
  { country: "Mauritius", code: "MU", currency: "MUR", symbol: "₨", name: "Mauritian Rupee" },
  { country: "Mexico", code: "MX", currency: "MXN", symbol: "$", name: "Mexican Peso" },
  { country: "Moldova", code: "MD", currency: "MDL", symbol: "L", name: "Moldovan Leu" },
  { country: "Monaco", code: "MC", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Mongolia", code: "MN", currency: "MNT", symbol: "₮", name: "Mongolian Tögrög" },
  { country: "Montenegro", code: "ME", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Morocco", code: "MA", currency: "MAD", symbol: "د.م.", name: "Moroccan Dirham" },
  { country: "Mozambique", code: "MZ", currency: "MZN", symbol: "MT", name: "Mozambican Metical" },
  { country: "Myanmar", code: "MM", currency: "MMK", symbol: "Ks", name: "Burmese Kyat" },
  { country: "Namibia", code: "NA", currency: "NAD", symbol: "$", name: "Namibian Dollar" },
  { country: "Nauru", code: "NR", currency: "AUD", symbol: "$", name: "Australian Dollar" },
  { country: "Nepal", code: "NP", currency: "NPR", symbol: "₨", name: "Nepalese Rupee" },
  { country: "Netherlands", code: "NL", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "New Zealand", code: "NZ", currency: "NZD", symbol: "$", name: "New Zealand Dollar" },
  { country: "Nicaragua", code: "NI", currency: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
  { country: "Niger", code: "NE", currency: "XOF", symbol: "Fr", name: "West African CFA Franc" },
  { country: "Nigeria", code: "NG", currency: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { country: "North Korea", code: "KP", currency: "KPW", symbol: "₩", name: "North Korean Won" },
  { country: "North Macedonia", code: "MK", currency: "MKD", symbol: "ден", name: "Macedonian Denar" },
  { country: "Norway", code: "NO", currency: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { country: "Oman", code: "OM", currency: "OMR", symbol: "ر.ع.", name: "Omani Rial" },
  { country: "Pakistan", code: "PK", currency: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  { country: "Palau", code: "PW", currency: "USD", symbol: "$", name: "United States Dollar" },
  { country: "Palestine", code: "PS", currency: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { country: "Panama", code: "PA", currency: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
  { country: "Papua New Guinea", code: "PG", currency: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
  { country: "Paraguay", code: "PY", currency: "PYG", symbol: "₲", name: "Paraguayan Guaraní" },
  { country: "Peru", code: "PE", currency: "PEN", symbol: "S/.", name: "Peruvian Sol" },
  { country: "Philippines", code: "PH", currency: "PHP", symbol: "₱", name: "Philippine Peso" },
  { country: "Poland", code: "PL", currency: "PLN", symbol: "zł", name: "Polish Złoty" },
  { country: "Portugal", code: "PT", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Qatar", code: "QA", currency: "QAR", symbol: "ر.ق", name: "Qatari Riyal" },
  { country: "Romania", code: "RO", currency: "RON", symbol: "lei", name: "Romanian Leu" },
  { country: "Russia", code: "RU", currency: "RUB", symbol: "₽", name: "Russian Ruble" },
  { country: "Rwanda", code: "RW", currency: "RWF", symbol: "Fr", name: "Rwandan Franc" },
  { country: "Saint Kitts and Nevis", code: "KN", currency: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { country: "Saint Lucia", code: "LC", currency: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { country: "Saint Vincent and the Grenadines", code: "VC", currency: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { country: "Samoa", code: "WS", currency: "WST", symbol: "T", name: "Samoan Tālā" },
  { country: "San Marino", code: "SM", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "São Tomé and Príncipe", code: "ST", currency: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra" },
  { country: "Saudi Arabia", code: "SA", currency: "SAR", symbol: "ر.س", name: "Saudi Riyal" },
  { country: "Senegal", code: "SN", currency: "XOF", symbol: "Fr", name: "West African CFA Franc" },
  { country: "Serbia", code: "RS", currency: "RSD", symbol: "дин.", name: "Serbian Dinar" },
  { country: "Seychelles", code: "SC", currency: "SCR", symbol: "₨", name: "Seychellois Rupee" },
  { country: "Sierra Leone", code: "SL", currency: "SLL", symbol: "Le", name: "Sierra Leonean Leone" },
  { country: "Singapore", code: "SG", currency: "SGD", symbol: "$", name: "Singapore Dollar" },
  { country: "Slovakia", code: "SK", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Slovenia", code: "SI", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Solomon Islands", code: "SB", currency: "SBD", symbol: "$", name: "Solomon Islands Dollar" },
  { country: "Somalia", code: "SO", currency: "SOS", symbol: "Sh", name: "Somali Shilling" },
  { country: "South Africa", code: "ZA", currency: "ZAR", symbol: "R", name: "South African Rand" },
  { country: "South Korea", code: "KR", currency: "KRW", symbol: "₩", name: "South Korean Won" },
  { country: "South Sudan", code: "SS", currency: "SSP", symbol: "£", name: "South Sudanese Pound" },
  { country: "Spain", code: "ES", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Sri Lanka", code: "LK", currency: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { country: "Sudan", code: "SD", currency: "SDG", symbol: "ج.س.", name: "Sudanese Pound" },
  { country: "Suriname", code: "SR", currency: "SRD", symbol: "$", name: "Surinamese Dollar" },
  { country: "Sweden", code: "SE", currency: "SEK", symbol: "kr", name: "Swedish Krona" },
  { country: "Switzerland", code: "CH", currency: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { country: "Syria", code: "SY", currency: "SYP", symbol: "£", name: "Syrian Pound" },
  { country: "Taiwan", code: "TW", currency: "TWD", symbol: "$", name: "New Taiwan Dollar" },
  { country: "Tajikistan", code: "TJ", currency: "TJS", symbol: "ЅМ", name: "Tajikistani Somoni" },
  { country: "Tanzania", code: "TZ", currency: "TZS", symbol: "Sh", name: "Tanzanian Shilling" },
  { country: "Thailand", code: "TH", currency: "THB", symbol: "฿", name: "Thai Baht" },
  { country: "Timor-Leste", code: "TL", currency: "USD", symbol: "$", name: "United States Dollar" },
  { country: "Togo", code: "TG", currency: "XOF", symbol: "Fr", name: "West African CFA Franc" },
  { country: "Tonga", code: "TO", currency: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
  { country: "Trinidad and Tobago", code: "TT", currency: "TTD", symbol: "$", name: "Trinidad and Tobago Dollar" },
  { country: "Tunisia", code: "TN", currency: "TND", symbol: "د.ت", name: "Tunisian Dinar" },
  { country: "Turkey", code: "TR", currency: "TRY", symbol: "₺", name: "Turkish Lira" },
  { country: "Turkmenistan", code: "TM", currency: "TMT", symbol: "m", name: "Turkmenistan Manat" },
  { country: "Tuvalu", code: "TV", currency: "AUD", symbol: "$", name: "Australian Dollar" },
  { country: "Uganda", code: "UG", currency: "UGX", symbol: "Sh", name: "Ugandan Shilling" },
  { country: "Ukraine", code: "UA", currency: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  { country: "United Arab Emirates", code: "AE", currency: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham" },
  { country: "United Kingdom", code: "GB", currency: "GBP", symbol: "£", name: "British Pound" },
  { country: "United States", code: "US", currency: "USD", symbol: "$", name: "United States Dollar" },
  { country: "Uruguay", code: "UY", currency: "UYU", symbol: "$", name: "Uruguayan Peso" },
  { country: "Uzbekistan", code: "UZ", currency: "UZS", symbol: "лв", name: "Uzbekistani Som" },
  { country: "Vanuatu", code: "VU", currency: "VUV", symbol: "Vt", name: "Vanuatu Vatu" },
  { country: "Vatican City", code: "VA", currency: "EUR", symbol: "€", name: "Euro" },
  { country: "Venezuela", code: "VE", currency: "VES", symbol: "Bs.", name: "Venezuelan Bolívar" },
  { country: "Vietnam", code: "VN", currency: "VND", symbol: "₫", name: "Vietnamese Đồng" },
  { country: "Yemen", code: "YE", currency: "YER", symbol: "﷼", name: "Yemeni Rial" },
  { country: "Zambia", code: "ZM", currency: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
  { country: "Zimbabwe", code: "ZW", currency: "ZWL", symbol: "$", name: "Zimbabwean Dollar" },
] as const;

const PHONE_CODES: Record<string, string> = {
  AF: "+93", AL: "+355", DZ: "+213", AD: "+376", AO: "+244", AI: "+1 264",
  AG: "+1 268", AR: "+54", AM: "+374", AW: "+297", AU: "+61", AT: "+43",
  AZ: "+994", BS: "+1 242", BH: "+973", BD: "+880", BB: "+1 246", BY: "+375",
  BE: "+32", BZ: "+501", BJ: "+229", BM: "+1 441", BT: "+975", BO: "+591",
  BA: "+387", BW: "+267", BR: "+55", BN: "+673", BG: "+359", BF: "+226",
  BI: "+257", KH: "+855", CM: "+237", CA: "+1", CV: "+238", KY: "+1 345",
  CF: "+236", TD: "+235", CL: "+56", CN: "+86", CO: "+57", KM: "+269",
  CG: "+242", CD: "+243", CR: "+506", CI: "+225", HR: "+385", CU: "+53",
  CW: "+599", CY: "+357", CZ: "+420", DK: "+45", DJ: "+253", DM: "+1 767",
  DO: "+1 809", TL: "+670", EC: "+593", EG: "+20", SV: "+503", GQ: "+240",
  ER: "+291", EE: "+372", SZ: "+268", ET: "+251", FJ: "+679", FI: "+358",
  FR: "+33", GA: "+241", GM: "+220", GE: "+995", DE: "+49", GH: "+233",
  GR: "+30", GD: "+1 473", GT: "+502", GN: "+224", GW: "+245", GY: "+592",
  HT: "+509", HN: "+504", HK: "+852", HU: "+36", IS: "+354", IN: "+91",
  ID: "+62", IR: "+98", IQ: "+964", IE: "+353", IL: "+972", IT: "+39",
  JM: "+1 876", JP: "+81", JO: "+962", KZ: "+7", KE: "+254", KI: "+686",
  KP: "+850", KR: "+82", KW: "+965", KG: "+996", LA: "+856", LV: "+371",
  LB: "+961", LS: "+266", LR: "+231", LY: "+218", LI: "+423", LT: "+370",
  LU: "+352", MO: "+853", MG: "+261", MW: "+265", MY: "+60", MV: "+960",
  ML: "+223", MT: "+356", MR: "+222", MU: "+230", MX: "+52", MD: "+373",
  MC: "+377", MN: "+976", ME: "+382", MA: "+212", MZ: "+258", MM: "+95",
  NA: "+264", NR: "+674", NP: "+977", NL: "+31", NZ: "+64", NI: "+505",
  NE: "+227", NG: "+234", MK: "+389", NO: "+47", OM: "+968", PK: "+92",
  PW: "+680", PS: "+970", PA: "+507", PG: "+675", PY: "+595", PE: "+51",
  PH: "+63", PL: "+48", PT: "+351", QA: "+974", RO: "+40", RU: "+7",
  RW: "+250", KN: "+1 869", LC: "+1 758", VC: "+1 784", WS: "+685", SM: "+378",
  ST: "+239", SA: "+966", SN: "+221", RS: "+381", SC: "+248", SL: "+232",
  SG: "+65", SK: "+421", SI: "+386", SB: "+677", SO: "+252", ZA: "+27",
  SS: "+211", ES: "+34", LK: "+94", SD: "+249", SR: "+597", SE: "+46",
  CH: "+41", SY: "+963", TW: "+886", TJ: "+992", TZ: "+255", TH: "+66",
  TG: "+228", TO: "+676", TT: "+1 868", TN: "+216", TR: "+90", TM: "+993",
  TV: "+688", UG: "+256", UA: "+380", AE: "+971", GB: "+44", US: "+1",
  UY: "+598", UZ: "+998", VU: "+678", VA: "+379", VE: "+58", VN: "+84",
  YE: "+967", ZM: "+260", ZW: "+263",
};

function codeToFlag(code: string) {
  if (code.length !== 2) return "🏳️";
  const A = 0x1f1e6;
  return String.fromCodePoint(A + code.charCodeAt(0) - 65, A + code.charCodeAt(1) - 65);
}

export const COUNTRIES: Country[] = COUNTRIES_CURRENCIES.map((c) => ({
  name: c.country,
  code: c.code,
  flag: codeToFlag(c.code),
  dial: PHONE_CODES[c.code] ?? "+",
  currency: c.currency,
  currencyName: c.name,
  currencySymbol: c.symbol,
})).sort((a, b) => a.name.localeCompare(b.name));

export const CURRENCIES = Array.from(
  new Map(COUNTRIES.map((c) => [c.currency, c])).values(),
).sort((a, b) => a.currency.localeCompare(b.currency));

const DEFAULT_COUNTRY = COUNTRIES.find((c) => c.code === "KE") ?? COUNTRIES[0];

export function findCountry(name: string | null | undefined): Country {
  if (!name) return DEFAULT_COUNTRY;
  return COUNTRIES.find((c) => c.name.toLowerCase() === name.toLowerCase()) ?? DEFAULT_COUNTRY;
}

export function formatCurrencyExample(currency: string) {
  try {
    return new Intl.NumberFormat("en", { style: "currency", currency, maximumFractionDigits: 2 }).format(1234.56);
  } catch {
    return `${currency} 1,234.56`;
  }
}
