/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletPlannerRouteImport } from './routes/_app/wallet-planner'
import { Route as AppSavingsRouteImport } from './routes/_app/savings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPersonalRouteImport } from './routes/_app/personal'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppMyBusinessesRouteImport } from './routes/_app/my-businesses'
import { Route as AppLendersRouteImport } from './routes/_app/lenders'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppBusinessPlansRouteImport } from './routes/_app/business-plans'
import { Route as AppBankAccountsRouteImport } from './routes/_app/bank-accounts'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppRoadmapsIndexRouteImport } from './routes/_app/roadmaps.index'
import { Route as AppBusinessesIndexRouteImport } from './routes/_app/businesses.index'
import { Route as AppAccountingIndexRouteImport } from './routes/_app/accounting/index'
import { Route as AppRoadmapsBusinessIdRouteImport } from './routes/_app/roadmaps.$businessId'
import { Route as AppBusinessesSlugRouteImport } from './routes/_app/businesses.$slug'
import { Route as AppAccountingReportsRouteImport } from './routes/_app/accounting/reports'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletPlannerRoute = AppWalletPlannerRouteImport.update({
  id: '/wallet-planner',
  path: '/wallet-planner',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPersonalRoute = AppPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMyBusinessesRoute = AppMyBusinessesRouteImport.update({
  id: '/my-businesses',
  path: '/my-businesses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLendersRoute = AppLendersRouteImport.update({
  id: '/lenders',
  path: '/lenders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBusinessPlansRoute = AppBusinessPlansRouteImport.update({
  id: '/business-plans',
  path: '/business-plans',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBankAccountsRoute = AppBankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoadmapsIndexRoute = AppRoadmapsIndexRouteImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBusinessesIndexRoute = AppBusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoadmapsBusinessIdRoute = AppRoadmapsBusinessIdRouteImport.update({
  id: '/roadmaps/$businessId',
  path: '/roadmaps/$businessId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBusinessesSlugRoute = AppBusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountingReportsRoute = AppAccountingReportsRouteImport.update({
  id: '/accounting/reports',
  path: '/accounting/reports',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/bank-accounts': typeof AppBankAccountsRoute
  '/business-plans': typeof AppBusinessPlansRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/lenders': typeof AppLendersRoute
  '/my-businesses': typeof AppMyBusinessesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/personal': typeof AppPersonalRoute
  '/profile': typeof AppProfileRoute
  '/savings': typeof AppSavingsRoute
  '/wallet-planner': typeof AppWalletPlannerRoute
  '/accounting/reports': typeof AppAccountingReportsRoute
  '/businesses/$slug': typeof AppBusinessesSlugRoute
  '/roadmaps/$businessId': typeof AppRoadmapsBusinessIdRoute
  '/accounting/': typeof AppAccountingIndexRoute
  '/businesses/': typeof AppBusinessesIndexRoute
  '/roadmaps/': typeof AppRoadmapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/bank-accounts': typeof AppBankAccountsRoute
  '/business-plans': typeof AppBusinessPlansRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/lenders': typeof AppLendersRoute
  '/my-businesses': typeof AppMyBusinessesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/personal': typeof AppPersonalRoute
  '/profile': typeof AppProfileRoute
  '/savings': typeof AppSavingsRoute
  '/wallet-planner': typeof AppWalletPlannerRoute
  '/accounting/reports': typeof AppAccountingReportsRoute
  '/businesses/$slug': typeof AppBusinessesSlugRoute
  '/roadmaps/$businessId': typeof AppRoadmapsBusinessIdRoute
  '/accounting': typeof AppAccountingIndexRoute
  '/businesses': typeof AppBusinessesIndexRoute
  '/roadmaps': typeof AppRoadmapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/bank-accounts': typeof AppBankAccountsRoute
  '/_app/business-plans': typeof AppBusinessPlansRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lenders': typeof AppLendersRoute
  '/_app/my-businesses': typeof AppMyBusinessesRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/personal': typeof AppPersonalRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/wallet-planner': typeof AppWalletPlannerRoute
  '/_app/accounting/reports': typeof AppAccountingReportsRoute
  '/_app/businesses/$slug': typeof AppBusinessesSlugRoute
  '/_app/roadmaps/$businessId': typeof AppRoadmapsBusinessIdRoute
  '/_app/accounting/': typeof AppAccountingIndexRoute
  '/_app/businesses/': typeof AppBusinessesIndexRoute
  '/_app/roadmaps/': typeof AppRoadmapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/bank-accounts'
    | '/business-plans'
    | '/contacts'
    | '/dashboard'
    | '/lenders'
    | '/my-businesses'
    | '/onboarding'
    | '/personal'
    | '/profile'
    | '/savings'
    | '/wallet-planner'
    | '/accounting/reports'
    | '/businesses/$slug'
    | '/roadmaps/$businessId'
    | '/accounting/'
    | '/businesses/'
    | '/roadmaps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/bank-accounts'
    | '/business-plans'
    | '/contacts'
    | '/dashboard'
    | '/lenders'
    | '/my-businesses'
    | '/onboarding'
    | '/personal'
    | '/profile'
    | '/savings'
    | '/wallet-planner'
    | '/accounting/reports'
    | '/businesses/$slug'
    | '/roadmaps/$businessId'
    | '/accounting'
    | '/businesses'
    | '/roadmaps'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/bank-accounts'
    | '/_app/business-plans'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/lenders'
    | '/_app/my-businesses'
    | '/_app/onboarding'
    | '/_app/personal'
    | '/_app/profile'
    | '/_app/savings'
    | '/_app/wallet-planner'
    | '/_app/accounting/reports'
    | '/_app/businesses/$slug'
    | '/_app/roadmaps/$businessId'
    | '/_app/accounting/'
    | '/_app/businesses/'
    | '/_app/roadmaps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet-planner': {
      id: '/_app/wallet-planner'
      path: '/wallet-planner'
      fullPath: '/wallet-planner'
      preLoaderRoute: typeof AppWalletPlannerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/personal': {
      id: '/_app/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof AppPersonalRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-businesses': {
      id: '/_app/my-businesses'
      path: '/my-businesses'
      fullPath: '/my-businesses'
      preLoaderRoute: typeof AppMyBusinessesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lenders': {
      id: '/_app/lenders'
      path: '/lenders'
      fullPath: '/lenders'
      preLoaderRoute: typeof AppLendersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/business-plans': {
      id: '/_app/business-plans'
      path: '/business-plans'
      fullPath: '/business-plans'
      preLoaderRoute: typeof AppBusinessPlansRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bank-accounts': {
      id: '/_app/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof AppBankAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roadmaps/': {
      id: '/_app/roadmaps/'
      path: '/roadmaps'
      fullPath: '/roadmaps/'
      preLoaderRoute: typeof AppRoadmapsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/businesses/': {
      id: '/_app/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof AppBusinessesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roadmaps/$businessId': {
      id: '/_app/roadmaps/$businessId'
      path: '/roadmaps/$businessId'
      fullPath: '/roadmaps/$businessId'
      preLoaderRoute: typeof AppRoadmapsBusinessIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/businesses/$slug': {
      id: '/_app/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof AppBusinessesSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounting/reports': {
      id: '/_app/accounting/reports'
      path: '/accounting/reports'
      fullPath: '/accounting/reports'
      preLoaderRoute: typeof AppAccountingReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBankAccountsRoute: typeof AppBankAccountsRoute
  AppBusinessPlansRoute: typeof AppBusinessPlansRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLendersRoute: typeof AppLendersRoute
  AppMyBusinessesRoute: typeof AppMyBusinessesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPersonalRoute: typeof AppPersonalRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppWalletPlannerRoute: typeof AppWalletPlannerRoute
  AppAccountingReportsRoute: typeof AppAccountingReportsRoute
  AppBusinessesSlugRoute: typeof AppBusinessesSlugRoute
  AppRoadmapsBusinessIdRoute: typeof AppRoadmapsBusinessIdRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
  AppBusinessesIndexRoute: typeof AppBusinessesIndexRoute
  AppRoadmapsIndexRoute: typeof AppRoadmapsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBankAccountsRoute: AppBankAccountsRoute,
  AppBusinessPlansRoute: AppBusinessPlansRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLendersRoute: AppLendersRoute,
  AppMyBusinessesRoute: AppMyBusinessesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPersonalRoute: AppPersonalRoute,
  AppProfileRoute: AppProfileRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppWalletPlannerRoute: AppWalletPlannerRoute,
  AppAccountingReportsRoute: AppAccountingReportsRoute,
  AppBusinessesSlugRoute: AppBusinessesSlugRoute,
  AppRoadmapsBusinessIdRoute: AppRoadmapsBusinessIdRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
  AppBusinessesIndexRoute: AppBusinessesIndexRoute,
  AppRoadmapsIndexRoute: AppRoadmapsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
